# Generated by Django 2.2 on 2020-10-22 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='genre',
            field=models.CharField(default='favorites', max_length=200),
        ),
    ]
