# Generated by Django 2.2 on 2020-10-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookdata_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdata',
            name='genre',
        ),
    ]
