# Generated by Django 2.2 on 2020-10-23 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_bookdata_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='image',
            field=models.ImageField(default='images/none/noimage.jpg', upload_to='images'),
        ),
    ]
