# Generated by Django 2.2 on 2020-10-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20201023_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
