# Generated by Django 2.2 on 2020-10-23 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20201023_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='rating',
            field=models.FloatField(),
        ),
    ]
